#!/usr/bin/python

from blacksmith import *

if __name__ == '__main__':
  verify_directory(ANVIL)
  print u'Downloading entire module catalog from {0}...'.format(FORGE),
  modules = PuppetModules(FORGE)
  print u'complete'

  for module in modules[:10]:
    print u'Downloading module {full_name}...'.format(**module),
    module.download()
    print u'complete'
    print u'Building spec file for module {full_name}...'.format(**module),
    module.generate_spec()
    print u'complete'
    print u'Building RPM for module {full_name}...'.format(**module),
    module.build_rpm()
    print u'complete'
    

