#!/usr/bin/python

from blacksmith import *

if __name__ == '__main__':
  verify_directory(ANVIL)

  module_list = download_modules_metadata(FORGE)

  modules = PuppetModules()

  for module in module_list[:10]:
    module = PuppetModule(**module)
    modules.append(module)
    print u'Downloading module {full_name}...'.format(**module),
    module.download()
    print u'complete'
    print u'Building spec file for module {full_name}...'.format(**module),
    module.generate_spec()
    print u'complete'
    