#!/usr/bin/python

from blacksmith import *

if __name__ == '__main__':
  verify_directory(anvil)

  module_list = download_modules_metadata(forge)

  modules = PuppetModules()

  for module in module_list[:10]:
    module = PuppetModule(**module)
    modules.append(module)
    print u'Downloading module {full_name}...'.format(**module),
    download_module(module)
    print u'complete'
